---

- name: restart cloudflared service
  become: true
  service:
    name: cloudflared
    enabled: true
    state: restarted

- name: restart ssh service
  become: true
  service:
    name: ssh
    enabled: true
    state: restarted

- name: restart nginx service
  become: true
  service:
    name: nginx
    enabled: true
    state: restarted

- name: update grub
  become: true
  command: update-grub

- name: restart apparmor service
  become: true
  service:
    name: apparmor
    enabled: true
    state: restarted
