---

- name: restart cloudflared service
  become: true
  service:
    name: cloudflared
    enabled: true
    state: restarted

- name: restart ssh service
  become: true
  service:
    name: ssh
    enabled: true
    state: restarted
