---

- name: download heroku install script
  get_url:
    url: https://cli-assets.heroku.com/install-ubuntu.sh
    dest: /tmp/heroku-install-ubuntu.sh

- file:
    path: /tmp/heroku-install-ubuntu.sh
    mode: '0700'

- name: install heroku cli
  become: true
  shell: /tmp/heroku-install-ubuntu.sh

- name: configure Heroku git remotes
  shell: "heroku git:remote --app={{ item.app }} --remote={{ item.remote }}"
  ignore_errors: yes # git remote might already exists
  args:
    chdir: "{{ bot_base_path }}/new-website"
  loop:
    - { app: cdnjs-new-website2, remote: heroku-web }
