---

- name: clone cdnjs's repos
  git:
    repo: "git@github.com:cdnjs/{{ item }}.git"
    dest: "/cdnjs-sven/{{ item }}"
    version: master
  loop:
    - script
    - bot
    - autoupdate
    - new-website
    - buildScript
    - web-minify-helper
    - SRIs
    - tools

- name: clone cdnjs repos
  git:
    repo: git@github.com:cdnjs/cdnjs.git
    dest: /cdnjs-sven/cdnjs
    update: no

- name: install npm deps
  shell: npm install
  args:
    chdir: "/cdnjs-sven/{{ item }}"
  loop:
    - web-minify-helper
    - cdnjs
    - autoupdate
    - tools

- name: symlink zopflipng-f
  become: true
  file:
    src: /cdnjs-sven/bot/scripts/zopflipng-f
    dest: /usr/bin/zopflipng-f
    state: link
    mode: '0777'
