---

- name: clone cdnjs's repos
  git:
    repo: "git@github.com:cdnjs/{{ item }}.git"
    dest: "/cdnjs-sven/{{ item }}"
    version: master
    force: true
  loop:
    - new-website
    - SRIs
    - tools
    - glob
    - packages
    - logs

- name: clone cdnjs
  git:
    repo: git@github.com:cdnjs/cdnjs.git
    dest: /cdnjs-sven/cdnjs
    update: no
    depth: 1

- name: install npm deps
  shell: npm install
  args:
    chdir: "/cdnjs-sven/{{ item }}"
  loop:
    - tools
    - glob
