---

- set_fact:
    tools:
      - packages
      - algolia
      - checker
      - autoupdate

- name: download tools
  get_url:
    force: true
    url: "https://github.com/cdnjs/tools/releases/latest/download/{{ item }}"
    dest: "/home/deploy/{{ item }}"
  loop: "{{ tools }}"

- name: make tools executable and owned by deploy
  file:
    owner: deploy
    group: deploy
    path: "/home/deploy/{{ item }}"
    mode: '0777'
  loop: "{{ tools }}"
