---

- name: store google cloud credential
  copy:
    dest: "~/google_storage_cdnjs_assets.json"
    content: "{{ google_storage_cdnjs_assets }}"

- set_fact:
    tools:
      - { name: packages, sha256: a926ba8e1baf9357683032fd4fcff9bb4d8a13cf36b315dde5bb07e3e7955586 }
      - { name: algolia, sha256: 72d26d3c2b36b7d920d10f679b286ab038d88715ae91cd89505009c5bcc71557 }

- name: download tools
  become: true
  get_url:
    url: "https://s3.that-test.site/cdnjs/{{ item.name }}"
    dest: "/usr/local/bin/{{ item.name }}"
    checksum: "sha256:{{ item.sha256 }}"
  loop: "{{ tools }}"

- name: make tools executable
  become: true
  file:
    path: "/usr/local/bin/{{ item.name }}"
    mode: '0777'
  loop: "{{ tools }}"
