---

- stat:
    path: /home/sven/google_storage_cdnjs_assets.json
  register: json
- name: store google cloud credential
  copy:
    dest: /home/sven/google_storage_cdnjs_assets.json
    content: "{{ google_storage_cdnjs_assets }}"
  when: not json.stat.exists

- set_fact:
    tools:
      - packages
      - algolia
      - checker
      - autoupdate

- name: download tools
  become: true
  get_url:
    force: true
    url: "https://github.com/cdnjs/tools/releases/latest/download/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
  loop: "{{ tools }}"

- name: make tools executable
  become: true
  file:
    path: "/usr/local/bin/{{ item }}"
    mode: '0777'
  loop: "{{ tools }}"
