---

- name: store google cloud credential
  copy:
    dest: "~/google_storage_cdnjs_assets.json"
    content: "{{ google_storage_cdnjs_assets }}"

- set_fact:
    tools:
      - { name: packages, sha256: 7f7a9fe2a63d31c2ab8f9d5f3697893a7922e976155516285f8473af1a7f1765 }
      - { name: algolia, sha256: 72d26d3c2b36b7d920d10f679b286ab038d88715ae91cd89505009c5bcc71557 }
      - { name: infralog, sha256: bb665e10d28cf5f14849f28b9909bd9c0346c09dcf1e50a291a2cbeb3119c1eb }

- name: download tools
  become: true
  get_url:
    url: "https://s3.that-test.site/cdnjs/{{ item.name }}"
    dest: "/usr/local/bin/{{ item.name }}"
    checksum: "sha256:{{ item.sha256 }}"
  loop: "{{ tools }}"

- name: make tools executable
  become: true
  file:
    path: "/usr/local/bin/{{ item.name }}"
    mode: '0777'
  loop: "{{ tools }}"
