---

- name: store google cloud credential
  copy:
    dest: "~/google_storage_cdnjs_assets.json"
    content: "{{ google_storage_cdnjs_assets }}"

- set_fact:
    tools:
      - packages
      - algolia
      - checker

- name: download tools
  become: true
  get_url:
    force: true
    url: "https://github.com/cdnjs/tools/releases/latest/download/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
  loop: "{{ tools }}"

- name: make tools executable
  become: true
  file:
    path: "/usr/local/bin/{{ item }}"
    mode: '0777'
  loop: "{{ tools }}"
