---

- set_fact:
    timers:
        - update-website
        - cdnjs-bot

- name: generate systemd timer's services
  become: true
  template:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
  loop: "{{ timers }}"

- name: generate systemd timers
  become: true
  template:
    src: "{{ item }}.timer"
    dest: "/etc/systemd/system/{{ item }}.timer"
  loop: "{{ timers }}"

- name: enable systemd timers
  become: true
  systemd:
    daemon_reload: yes
    name: "{{ item }}.timer"
    enabled: yes
    state: started
  loop: "{{ timers }}"
