---

- name: generate update script
  template:
    src: update-website.sh
    dest: ~/update-website.sh

# - name: collect bot logs
#   cron:
#     name: collect bot logs
#     special_time: daily
#     job: "infralog push-and-truncate bot {{ bot_log_file }}"
#     user: sven
