alias b="byobu"
alias gco="git checkout"
alias gst="git status"
alias s="sudo"
alias gp="git push"
alias gd="git diff"
alias ga="git add"
alias gcm="git checkout master"
alias nr="npm run"
alias gsta='git stash push'
alias gstp='git stash pop'
